### ISSUE TITLE
Video Tutorials do not play

### ISSUE THREAD

**Issue by jvermaas** [durrantlab/blendmol#1]
The error message points to either "Content Length Exceeded" or "Error Fetching Resource". Any chance these videos are uploaded to youtube somewhere?

**Comment by jacobdurrant** [comment]
Thanks for bringing this to my attention. The videos should work now (README.md from main branch): https://github.com/durrantlab/blendmol/blob/master/README.md

**Comment by jvermaas** [comment]
Thanks! They work now!
